FROM python:3.8

WORKDIR /trias_extractor

RUN pip3 install --no-cache-dir --upgrade pip

COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["gunicorn","-w","2","--threads","2","-b","0.0.0.0:5000","trias_extractor:app"]