version: "3.9"
services:
  trias-extractor:
    container_name: trias-extractor
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./code:/code
    environment:
      FLASK_ENV: development
  cache:
    container_name: cache
    image: "redis:alpine"
    volumes:
      - ./redis-data:/data
    # ports:
    #  - "6379:6379"
    entrypoint: ["redis-server", "--appendonly", "yes"]